default_agent: sales_copilot_history_agent
agents:
  sales_copilot_history_agent:
    name: sales_copilot_history_agent
    entrypoint: C:/Users/nikhil.patil/Desktop/Sales-Copilet-Code/Deployed_Agents/History_Agent/history_agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: podman
    source_path: C:\Users\nikhil.patil\Desktop\Sales-Copilet-Code\Deployed_Agents\History_Agent
    aws:
      execution_role: arn:aws:iam::969385807621:role/AgentCoreRuntimeRole
      execution_role_auto_create: true
      account: '969385807621'
      region: us-east-1
      ecr_repository: 969385807621.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-sales_copilot_history_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: sales_copilot_history_agent-gEUQWn7MRd
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:969385807621:runtime/sales_copilot_history_agent-gEUQWn7MRd
      agent_session_id: 5b242985-cf61-4917-80f2-ff2476570fa0
    codebuild:
      project_name: bedrock-agentcore-sales_copilot_history_agent-builder
      execution_role: arn:aws:iam::969385807621:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-993e6e792c
      source_bucket: bedrock-agentcore-codebuild-sources-969385807621-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: sales_copilot_history_agent_mem-Kpo1azD29R
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:969385807621:memory/sales_copilot_history_agent_mem-Kpo1azD29R
      memory_name: sales_copilot_history_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
