version: 0.2

env:
  variables:
    S3_BUCKET: "sales-copilot-ui-bucket"
    CLOUDFRONT_DISTRIBUTION_ID: "E3A3BNSRWFHF9V"
    BUILD_OUTPUT_DIR: "dist"
    AWS_REGION: "us-east-1"
    GIT_BRANCH: "main"
    NODE_VERSION: "10"
    INVALIDATION_PATHS: "/*"
    CACHE_CONTROL_STATIC: "public, max-age=31536000, immutable"
    CACHE_CONTROL_HTML: "public, max-age=3600, must-revalidate"

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "=== INSTALL PHASE ==="
      - pwd

      - |
          if ! command -v aws &> /dev/null; then
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install
          fi

      - node --version
      - npm --version
      - aws --version

  pre_build:
    commands:
      - npm ci
      - npm audit --production || true

  build:
    commands:
      - npm run build
      - |
          echo "Build ID: $CODEBUILD_BUILD_ID" > $BUILD_OUTPUT_DIR/build-info.txt
          echo "Commit: $(git rev-parse HEAD || echo unknown)" >> $BUILD_OUTPUT_DIR/build-info.txt
          echo "Build Date: $(date)" >> $BUILD_OUTPUT_DIR/build-info.txt

  post_build:
    commands:
      - |
          if [ ! -d "$BUILD_OUTPUT_DIR" ]; then
            echo "ERROR: Build output directory not found"
            exit 1
          fi

      - |
          aws s3 sync $BUILD_OUTPUT_DIR/ s3://$S3_BUCKET/ \
            --exclude "*.html" \
            --cache-control "$CACHE_CONTROL_STATIC" \
            --delete

      - |
          aws s3 sync $BUILD_OUTPUT_DIR/ s3://$S3_BUCKET/ \
            --include "*.html" \
            --cache-control "$CACHE_CONTROL_HTML" \
            --delete

      - |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "$INVALIDATION_PATHS"

artifacts:
  files:
    - '**/*'
  base-directory: $BUILD_OUTPUT_DIR

cache:
  paths:
    - node_modules/**/*
